### ISSUE TITLE
Append compiled version by the github release

### ISSUE THREAD

**Issue by JackLeo** [arturbosch/sonar-kotlin#13]
Most SonarQube plugins append jar file to the release. This makes easy to automate by just doing wget/curl and getting the file rather than compiling and then moving it.

Examples:
https://github.com/Backelite/sonar-swift/releases
https://github.com/ofields/sonar-android/releases

**Comment by arturbosch** [comment]
Will do with next release, thanks for the feedback. I will try to release an updated version in the next days after RC2 release of detekt.

**Comment by JackLeo** [comment]
Thanks! Good to see an active project :)

**Comment by arturbosch** [comment]
0.2.1 is up with updated detekt (+ new rules), the jar is included. Thanks for the feedback!
