### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by JackLeo** [arturbosch/sonar-kotlin#22]
Hi, just another piece of feedback. It's great that you keep https://github.com/arturbosch/sonar-kotlin/blob/master/CHANGELOG.md up to date, would be great that the same notes would be part of the release notes when drafting a release https://github.com/arturbosch/sonar-kotlin/releases/tag/0.2.2. Minor gripe, but would make it a bit easier :)

Example:
https://github.com/Backelite/sonar-swift/releases/tag/0.3.5

**Comment by arturbosch** [comment]
Will try to add release notes to the github tags :). See 0.2.3 I just uploaded :D

**Comment by JackLeo** [comment]
yeah I know, luck had it that I've downloaded and put your release to our prod within first 30 mins of it being released since I had to update the swift plugin as well.

**Comment by arturbosch** [comment]
Good to see that someone uses it :D

**Comment by JackLeo** [comment]
I'm closing this ticket since https://github.com/arturbosch/sonar-kotlin/releases/tag/0.2.3 addresses the issue
