### ISSUE TITLE
Add line length setting for detekt-kotlin:MaxLineLength

### ISSUE THREAD

**Issue by thevery** [arturbosch/sonar-kotlin#23]

**Comment by arturbosch** [comment]
You can set the MaxLineLength inside a detekt.yml configuration. If you put that config inside your project, the sonar-kotlin plugin can pick it up inside your project `<Your_Project>/Management/Kotlin/Detekt config path` (absolute path only works for now). As mentioned in #12 sonar treats each sub project as an analysis and the config file is not found.

I will figure out the best way to deal with that and write documentation for the configuration part in 0.3.0.

**Comment by arturbosch** [comment]
The fix in #12 will let you successfully use the detekt config to specify the max line length.
