### ISSUE TITLE
NOSONAR not working 

### ISSUE THREAD

**Issue by jllado** [arturbosch/sonar-kotlin#32]
With the NOSONAR comment, Sonarqube should skip the issue. But it's no working with the kotlin issues.

**Comment by arturbosch** [comment]
Ok, didn't know there was something for sonar. I use `detekt` as the underlying code smell tool which has not much to do with sonar api's. detekt uses a `baseline.xml` or the `@Suppress(RULE_NAME)` annotation to ignore them. Please check out the github project for detekt.

**Comment by arturbosch** [comment]
I will close this, as I do not plan to support the `NOSONAR` comment. Please the detekt mechanisms.
