### ISSUE TITLE
SonarQube integration is not working

### ISSUE THREAD

**Issue by legendjaks** [arturbosch/sonar-kotlin#35]
Even `sonar-kotlin` project is not working with SonarQube. Try to clone this project and run `'./gradlew sonarqube'`, following error is thrown

```
io.gitlab.arturbosch.detekt.sonar.jacoco.KotlinJaCoCoSensor has unsatisfied dependency 
    'interface org.sonar.plugins.java.api.JavaResourceLocator' for constructor 
    'public io.gitlab.arturbosch.detekt.sonar.jacoco.KotlinJaCoCoSensor(org.sonar.api.batch.fs.FileSystem,org.sonar.plugins.java.api.JavaResourceLocator,org.sonar.java.JavaClasspath)' 
    from org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer
```

**Comment by arturbosch** [comment]
Can't reproduce it. Just cloned and run with wrapper and without. Both works for me.

![2017-10-22-132651_1005x336_scrot](https://user-images.githubusercontent.com/20924106/31861400-cd3a77c2-b72c-11e7-9e12-38b99a8cfd91.png)
![2017-10-22-132731_1894x761_scrot](https://user-images.githubusercontent.com/20924106/31861401-cd5560d2-b72c-11e7-8309-2a1106cfbf51.png)

**Comment by legendjaks** [comment]
Earlier I was getting the above-mentioned errors. Now I tried and it is working without any issue. Thanks.

**Comment by asgarddesigns** [comment]
I am experiencing the same issue with our build...

```
Execution failed for task ':sonarqube'.
> io.gitlab.arturbosch.detekt.sonar.jacoco.KotlinJaCoCoSensor has unsatisfied dependency 'interface org.sonar.plugins.java.api.JavaResourceLocator' for constructor 'public io.gitlab.arturbosch.detekt.sonar.jacoco.KotlinJaCoCoSensor(org.sonar.api.batch.fs.FileSystem,org.sonar.plugins.java.api.JavaResourceLocator,org.sonar.java.JavaClasspath)' from org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@28e2b880:135<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@5ed5f298:218<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@4b9d429f:7<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@2a05dc15:32<|
```

 @legendjaks did  you find any reason for this to fail?

**Comment by asgarddesigns** [comment]
So after some more investigation, it looks like the sonar-java plugin had been dropped during a rebuild, causing this error.

Would it be worth catching and throwing a better error? Or maybe this is solvable via the API?

Happy to do the work if someone can give me a headstart with the best way to do that...

**Comment by juancarloscruz** [comment]
Same here using SonarQube 6.7.1 with sonar-kotlin 0.4.1 and sonarqube-gradle-plugin:2.6.2. No idea where to start to investigate.

**Comment by arturbosch** [comment]
What does the `logs` folder say? Something inside `web.log`?

**Comment by juancarloscruz** [comment]
Hi Artur,
There's nothing remarkable in the SonarQube server logs (only some notices from the DetektPlugin initialization).

The error only happens on clients running sonar-scanner, no matter they actually use the Kotlin plugin for the current project or not. I have to completely disable the plugin on the server in order to have sonar-scanners in working condition.

**Comment by arturbosch** [comment]
Ok, that looks like a dependency injection error. Unfortunately with the same versions I cannot reproduce it ...
Did you downloaded 0.4.1 or built it by yourself?

**Comment by juancarloscruz** [comment]
I tried the 0.4.1 from the release section. Too bad.
Anyway, thanks for your efforts!
