### ISSUE TITLE
Code coverage sample project

### ISSUE THREAD

**Issue by marcinbak** [arturbosch/sonar-kotlin#46]
@vexdev  @arturbosch I've been trying to configure my Android project to work with sonar-kotlin and it looks good when it comes to reporting issues, however none of the comments and suggestions helped me to make code coverage show up in SonarQube. Even comments that claim to make it work are either incomplete or I miss something obvious.

The only hint I get is:

> Analysing android-sonar-kotlin/app/build/jacoco/testDebugUnitTest.exec
> Coverage information was not collected. Perhaps you forget to include debug information into compiled classes?

But that doesn't help much.

I've prepared a sample project with configuration I use and it would be awesome if someone could make it work.
https://github.com/marcinbak/android-sonar-kotlin

**Comment by artpick** [comment]
Hi,
I did struggle a bit with that too, I have a working project with sonar jacoco for kotlin.
https://github.com/artpick/kotlin-sonar-jacoco
Checkout the warnings at the end ;)
Enjoy

**Comment by marcinbak** [comment]
Thanks, I will try it asap. After quick check I see you're using Jacoco 0.8.0 that was released 13 days ago, so maybe this did the trick.

**Comment by marcinbak** [comment]
Made it finally work. You can check my project for reference https://github.com/marcinbak/android-sonar-kotlin

**Comment by imspatni** [comment]
@marcinbak Thanks for your post, but I'm getting:
> Task :sonarqube
SCM provider autodetection failed. No SCM provider claims to support this project. Please use sonar.scm.provider to define SCM of your project.
Analyzing 2 kotlin files: 
Coverage information was not collected. Perhaps you forget to include debug information into compiled classes?


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sonarqube'.
> File app/src/main/java/de/neofonie/androidsonarkotlin/MainActivity.kt can't be indexed twice. Please check that inclusion/exclusion patterns produce disjoint sets for main and test files

I have cloned your project without any character modification. Could you please share your knowledge on this !!

**Comment by Shubhampatni86** [comment]
@marcinbak Thanks for your post, but I'm getting:
> Task :sonarqube
SCM provider autodetection failed. No SCM provider claims to support this project. Please use sonar.scm.provider to define SCM of your project.
Analyzing 2 kotlin files: 
Coverage information was not collected. Perhaps you forget to include debug information into compiled classes?


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sonarqube'.
> File app/src/main/java/de/neofonie/androidsonarkotlin/MainActivity.kt can't be indexed twice. Please check that inclusion/exclusion patterns produce disjoint sets for main and test files

I have cloned your project without any character modification. Could you please share your knowledge on this !!

**Comment by mdenissov** [comment]
> I have cloned your project without any character modification. Could you please share your knowledge on this !!

+1 I have the same error. I have tried it on sonar 6 and 7 versions.

Result is:
> File app/src/main/java/de/neofonie/androidsonarkotlin/MainActivity.kt can't be indexed twice. Please check that inclusion/exclusion patterns produce disjoint sets for main and test files

**Comment by marcinbak** [comment]
@mdenissov  @Shubhampatni86 cleaned up the project and fixed all the issues. Now with Jacoco Sonarqube plugin it was easier to achieve.
