### ISSUE TITLE
What was the reasoning behind TooGenericExceptionCaught?

### ISSUE THREAD

**Issue by CodyEngel** [arturbosch/sonar-kotlin#50]
I recently wrote a data structure that helps to encapsulate a 2D array. One function I have is to test if something exists, part of that is catching `IndexOutOfBoundsException` because if it is thrown then clearly the item doesn't exist. Unfortunately Detekt will give a critical warning detekt-kotlin:TooGenericExceptionCaught and it recommends that I use my own exception. This seems strange because the exception is derived from ArrayList and I have no control over it.

Example:

```kotlin
fun exists(verticalIndex: Int, horizontalIndex): Boolean {
    return try {
         multiDimensionArray[verticalIndex][horizontalIndex] != null
    } catch (e: IndexOutOfBoundsException) { // Detekt doesn't like this catch.
         false
    }
}
```

**Comment by arturbosch** [comment]
Please use the detekt issue board for such questions - [detekt repo](https://github.com/arturbosch/detekt.

**Comment by arturbosch** [comment]
Well, you should not catch RuntimeException as they should be only thrown when the system can not recover itself. Clearly IndexOutOfBoundExceptions can be avoided by testing the boundaries. It always feel a bit hacky when catching such an error and saying it is ok in my case and move on :)
