### ISSUE TITLE
No jacoco coverage for java classes tested by kotlin tests

### ISSUE THREAD

**Issue by kzaikin** [arturbosch/sonar-kotlin#52]
We have Java for production and we try Kotlin for unit tests.
Java tests coverage is fine in Sonar while coverage by Kotlin tests is missing.
Kotlin tests coverage should be available in sonar too

**Comment by arturbosch** [comment]
In detekt up from RC5 a `test-pattern` concept was introduced which allows to turn off rules for only test paths.
sonar-kotlin while using RC5 and up has forgot to remove the path filter from the defaults:

`const val PATH_FILTERS_DEFAULTS = ".*/test/.*,.*/resources/.*,.*/build/.*,.*/target/.*"`

Thanks for reporting. After detekt RC6-2, I will try to fix this and release a new sonar-kotlin version too.

**Comment by kzaikin** [comment]
This is no more an issue, coverage is fine
