### ISSUE TITLE
Spread operator in SpringApplicationBuilder

### ISSUE THREAD

**Issue by ashofthephoenix** [arturbosch/sonar-kotlin#57]
Hello,
I asked a question on stackoverflow already, so if you don't mind, I'll paste it here:

https://stackoverflow.com/questions/48369495/kotlin-spread-operator-in-springapplicationbuilder

Should this be ignored? Thanks.

**Comment by arturbosch** [comment]
This is unfortunately a limited of detekt at the moment. 
It flags SpreadOperator-Usage in library code, which you do not have access to refactor the function.
When we have type resolving, we will not report such cases.
So the first answer on stackoverflow is right, you can suppress the finding or add it to the detekt baseline.
