### ISSUE TITLE
sonar-kotlin support in SonarQube 5.6.7

### ISSUE THREAD

**Issue by geneemelyanov** [arturbosch/sonar-kotlin#63]
The Readme says that sonar-kotlin supports SonarQube 5.6.7, but I tried with that version and it failed to start with this error:
```
web[o.a.c.c.C.[.[.[/]] Exception sending context initialized event to listener instance of class org.sonar.server.platform.PlatformServletContextListener
org.sonar.api.utils.MessageException: Plugin Kotlin [kotlin] requires at least SonarQube 6.7
```
Is there any additional configuration needed?

**Comment by arturbosch** [comment]
Nope, the readme is out of date. Sorry!
SonarQube dropped support for that version, so did I in 0.4
