### ISSUE TITLE
mvn package errors

### ISSUE THREAD

**Issue by tr01010** [arturbosch/sonar-kotlin#69]
Hi!
There are some errors while trying `mvn package`.

> 
> [INFO] Running io.gitlab.arturbosch.detekt.sonar.sensor.DetektSensorTest
> [ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.469 s <<< FAILURE! - in io.gitlab.arturbosch.detekt.sonar.sensor.DetektSensorTest
> [ERROR] measures a single kotlin file(io.gitlab.arturbosch.detekt.sonar.sensor.DetektSensorTest)  Time elapsed: 0.382 s  <<< ERROR!
> org.mockito.exceptions.base.MockitoException: 
> 
> Mockito cannot mock this class: interface org.sonar.api.measures.FileLinesContextFactory.
> 
> Mockito can only mock non-private & non-final classes.
> If you're not sure why you're getting this error, please report to the mailing list.
> 
> 
> Java               : 10
> JVM vendor name    : "Oracle Corporation"
> JVM vendor version : 10.0.1+10
> JVM name           : Java HotSpot(TM) 64-Bit Server VM
> JVM version        : 10.0.1+10
> JVM info           : mixed mode
> OS name            : Mac OS X
> OS version         : 10.13.5
> 
> 
> Underlying exception : java.lang.UnsupportedOperationException: Cannot define class using reflection
> 	at io.gitlab.arturbosch.detekt.sonar.sensor.DetektSensorTest.setUp(DetektSensorTest.kt:101)
> Caused by: java.lang.UnsupportedOperationException: Cannot define class using reflection
> 	at io.gitlab.arturbosch.detekt.sonar.sensor.DetektSensorTest.setUp(DetektSensorTest.kt:101)
> Caused by: java.lang.IllegalArgumentException: Unknown Java version: 10
> 	at io.gitlab.arturbosch.detekt.sonar.sensor.DetektSensorTest.setUp(DetektSensorTest.kt:101)
> 
> [ERROR] measures two classes(io.gitlab.arturbosch.detekt.sonar.sensor.DetektSensorTest)  Time elapsed: 0.02 s  <<< ERROR!
> org.mockito.exceptions.base.MockitoException: 
> 
> Mockito cannot mock this class: interface org.sonar.api.measures.FileLinesContextFactory.
> 
> Mockito can only mock non-private & non-final classes.
> If you're not sure why you're getting this error, please report to the mailing list.
> 
> 
> Java               : 10
> JVM vendor name    : "Oracle Corporation"
> JVM vendor version : 10.0.1+10
> JVM name           : Java HotSpot(TM) 64-Bit Server VM
> JVM version        : 10.0.1+10
> JVM info           : mixed mode
> OS name            : Mac OS X
> OS version         : 10.13.5
> 
> 
> Underlying exception : java.lang.UnsupportedOperationException: Cannot define class using reflection
> 	at io.gitlab.arturbosch.detekt.sonar.sensor.DetektSensorTest.setUp(DetektSensorTest.kt:101)
> Caused by: java.lang.UnsupportedOperationException: Cannot define class using reflection
> 	at io.gitlab.arturbosch.detekt.sonar.sensor.DetektSensorTest.setUp(DetektSensorTest.kt:101)
> Caused by: java.lang.IllegalArgumentException: Unknown Java version: 10
> 	at io.gitlab.arturbosch.detekt.sonar.sensor.DetektSensorTest.setUp(DetektSensorTest.kt:101)
> 
> [INFO] 
> [INFO] Results:
> [INFO] 
> [ERROR] Errors: 
> [ERROR]   DetektSensorTest.setUp:101 Mockito 
> Mockito cannot mock this class: interface ...
> [ERROR]   DetektSensorTest.setUp:101 Mockito 
> Mockito cannot mock this class: interface ...
> [INFO] 
> [ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0
> [INFO] 
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 5.991 s
> [INFO] Finished at: 2018-07-02T19:28:09+06:00
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (default-test) on project sonar-kotlin: There are test failures.
> [ERROR] 
> [ERROR] Please refer to /Users/user/path/sonar-kotlin/target/surefire-reports for the individual test results.
> [ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
> [ERROR] -> [Help 1]
> org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (default-test) on project sonar-kotlin: There are test failures.
> 
> Please refer to /Users/user/path/sonar-kotlin/target/surefire-reports for the individual test results.
> Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
>     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
>     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
>     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
>     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
>     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
>     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
>     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
>     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
>     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
>     at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
>     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
>     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
>     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke (Method.java:564)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
> Caused by: org.apache.maven.plugin.MojoFailureException: There are test failures.
> 
> Please refer to /Users/user/path/sonar-kotlin/target/surefire-reports for the individual test results.
> Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
>     at org.apache.maven.plugin.surefire.SurefireHelper.throwException (SurefireHelper.java:240)
>     at org.apache.maven.plugin.surefire.SurefireHelper.reportExecution (SurefireHelper.java:112)
>     at org.apache.maven.plugin.surefire.SurefirePlugin.handleSummary (SurefirePlugin.java:364)
>     at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked (AbstractSurefireMojo.java:1052)
>     at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute (AbstractSurefireMojo.java:868)
>     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
>     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
>     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
>     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
>     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
>     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
>     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
>     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
>     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
>     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
>     at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
>     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
>     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
>     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke (Method.java:564)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
> [ERROR] 
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] 
> 
> > http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException`
>

**Comment by limdale** [comment]
I also encountered the same problem, was able to run `mvn package` successfully after downgrading to Java 8. Most likely caused by the mockito-kotlin library
