### ISSUE TITLE
Jacoco code coverage shows as zero for kotlin 

### ISSUE THREAD

**Issue by DimuthuDeLanerolle** [arturbosch/sonar-kotlin#77]
When we run our gradle , kotlin unit tests jacoco code coverage report generation was successful , however we have noticed that sonarqube shows gradle , jacoco code coverage as 0 for kotlin tests. 

Below is the sonarQube.gradle file extract. Is there any way resolve this ?

sonarqube {
    properties {
        property "sonar.host.url", "https://xx/sonar"
        property "sonar.projectKey", "xxy:xxx"
        property "sonar.projectName", "xxxx"
        property "sonar.projectDescription", "xxxxx"
        property "sonar.projectVersion", "1.0"
        property "sonar.sourceEncoding", "UTF-8"
        property "sonar.jacoco.reportPaths", "$buildDir/jacoco/test.exec"
        property "sonar.buildbreaker.skip" , "false"
        property "sonar.projectBaseDir", "${project.projectDir}/src"
    }
}
![image](https://user-images.githubusercontent.com/41716876/45458874-164d8c80-b739-11e8-96e4-b4f8777e2c14.png)

kotlin-version  1.2.60
jacoco-version 0.8.2

**Comment by DimuthuDeLanerolle** [comment]
Hi Any update on this?

**Comment by arturbosch** [comment]
Have you used a self-build master version to test out jacoco?
If no please do it, because we merged some changes lately.
Unfortunately I do not have any time left for now to work on sonar-kotlin :(.

**Comment by DimuthuDeLanerolle** [comment]
I have tried out with the latest version however still was unable to get coverage stats. :(

**Comment by arturbosch** [comment]
Please try out 0.5.1 with the jacoco fix
