### ISSUE TITLE
how to use Ktlint with detekt

### ISSUE THREAD

**Issue by afaucogney** [arturbosch/sonar-kotlin#78]
Hi,

  When using detekt in the IDE, you can easily integrate Ktlint by adding detekt dependency. How may we do that in the case of sonar-plugin ?

```
dependencies {
    detekt "io.gitlab.arturbosch.detekt:detekt-formatting:[version]"
}
```

**Comment by arturbosch** [comment]
It is not possible for now sorry. There is #1 which should tackle this.

**Comment by rom4ek** [comment]
So, just to clarify [this one](https://rules.sonarsource.com/kotlin) is not the current repository right?

**Comment by arturbosch** [comment]
Hey @rom4ek, nope the official sonar-kotlin plugin is not our plugin. But their plugin allows to import detekt's report files to have both rule results inside the sonarqube.
I haven't used SonarLint so I don't know if they use the same plugins or not :/

**Comment by arturbosch** [comment]
I've just pushed a commit which integrates KtLint rules over detekt to sonar-kotlin -> 63643bc2d63225863725c98976624a5c470d3d0f
