### ISSUE TITLE
No duplications and no bugs showing in sonarqube

### ISSUE THREAD

**Issue by robinvanb** [arturbosch/sonar-kotlin#80]
Whenever I do an analysis it doesn't show any duplications or any bugs in sonarqube. Coverage is shown, however.

I'm using Sonarqube 7.1 and sonar-kotlin 0.5.1 and this is my configuration:

    sonarqube {
       properties {
        property "sonar.projectBaseDir", "$projectDir/.."
        property "sonar.exclusions", "build/generatedsources/**,build/xjc/**"
        property "sonar.jacoco.reportPaths", "$projectDir/build/jacoco/mergeJacoco.exec"
        property 'sonar.sourceEncoding', 'UTF-8'
       }
    }
    ...
    subprojects {
        sonarqube {
        properties {
            property 'sonar.java.binaries', "$buildDir/classes/kotlin/main"
        }
     }
    }

Is my configuration incorrect or is this an issue?

**Comment by arturbosch** [comment]
This unofficial plugin does not support duplications or bugs. All detekt issues are shown as code smells.
The official plugin may support them. It also allows to import detekt issues :)
