### ISSUE TITLE
SonarQube Not Picking Up Kotlin Coverage

### ISSUE THREAD

**Issue by ZergHunter3000** [arturbosch/sonar-kotlin#83]
I am unable to get code coverage to appear for Kotlin files in SonarQube.  The coverage reports are generated by JaCoCo, and are visible in the outputted .html documents, indicating it does recognize that my Kotlin files are covered.  Yet, when running mvn sonar:sonar, only the Java coverage makes it through to SonarQube.  I also see Kotlin references in the jacoco.xml file.

My properties look as such:
```
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <java.version>1.8</java.version>
        <kotlin.version>1.3.0</kotlin.version>
        <kotlin.compiler.incremental>true</kotlin.compiler.incremental>

        <sonar.sources>src/main</sonar.sources>
        <sonar.tests>src/test</sonar.tests>

        <sonar.sources>src/main</sonar.sources>
        <sonar.tests>src/test</sonar.tests>
        <sonar.java.binaries>${project.basedir}\target</sonar.java.binaries>
        <sonar.kotlin.binaries>app/build/tmp/kotlin-classes</sonar.kotlin.binaries>
        <!-- Below property indicates the pattern of the test suite -->
        <runSuite>**/*Suite.class</runSuite>
        <!-- Sonar-JaCoCo properties -->
        <sonar.java.coveragePlugin>jacoco</sonar.java.coveragePlugin>
        <sonar.kotlin.coveragePlugin>jacoco</sonar.kotlin.coveragePlugin>
        <sonar.jacoco.reportPaths>${project.basedir}\target\jacoco.exec</sonar.jacoco.reportPaths>
```

I also am running versions:
JaCoCo v0.8.2
Sonar-Kotlin v0.5.2
SonarQube 7+ (have tried 6 as well)

Any thoughts or ideas on this weird situation?

**Comment by Christian-Schroeder** [comment]
Hey, having the same problem here, since august there are no coverage reports anymore...

**Comment by ZergHunter3000** [comment]
Update; I made it further, it wasn't properly pulling in the plugin for some reason.  However, I did end up getting stuck on what seems to be an issue with detekt:
```
[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.5.0.1254:sonar (default-cli) on project eems-server: The rule 'DetektRuleKey(repositoryKey=detekt-kotlin, ruleKey=ConstructorParameterNaming, active=true, issue=Issue(id='ConstructorParameterNaming', severity=Style, debt=5min))' does not exist. -> [Help 1]
```

Still rather confusing.

**Comment by Jendrekpl** [comment]
Any updates?

**Comment by arturbosch** [comment]
@ZergHunter3000 do you have more stacktraces for me?
Hm `ConstructorParameterNaming` is a rather new rule (August) but should be inside version `0.5.2`.
A minimal kotlin project where jacoco is configured would help debugging.

**Comment by arturbosch** [comment]
This should be fixed in master now. Feel free to reopen if it does not work for you in the next version.

**Comment by sylhare** [comment]
If you have issues with Kotlin coverage not taken by sonar when having a mixed source project (java and kotlin).
It might be just a gradle configuration to do:
[Sonarqube not picking up both Kotlin and Java Coverage gradle project](https://stackoverflow.com/questions/59076853/sonarqube-not-picking-up-both-kotlin-and-java-coverage-gradle-project/59076854#59076854)
