### ISSUE TITLE
Can this plugin be used as a Sonarlint-cli plugin?

### ISSUE THREAD

**Issue by violinday** [arturbosch/sonar-kotlin#89]
I tried to put sonar-kotlin-0.4.2.jar  in the soanrlint-cli "plugins" folder and detected the kotlin problem as a plugin, but not work.

Sorry, I didn't find a way to debug the Soanrlint-cli plugin using Intellij IDEA.

What should I do to get it to work and detect problems?

Thanks. ：）

**Comment by violinday** [comment]
The problem was solved by modifying sonar-kotlin's code.

**Comment by arturbosch** [comment]
Heyho, glad that you could solve this. Please consider to open a PR with your solution.
