### ISSUE TITLE
sonar.sh doesn't exist

### ISSUE THREAD

**Issue by IgorGanapolsky** [arturbosch/sonar-kotlin#94]
Hello,
I am following your README.  It says to 
> cd $SONAR_HOME/bin/[your_os]
   ./sonar.sh restart

However, on my Mac's **SONAR_HOME/bin** directory, there is only:
sonar-scanner           sonar-scanner-debug

Please advise,
Igor

**Comment by arturbosch** [comment]
Hi,
have you installed sonar from this url https://www.sonarqube.org/downloads/ ?
If I extract the zip, I get there a `bin/macosx-universal-64` folder which has a `sonar.sh` file.

**Comment by IgorGanapolsky** [comment]
I downloaded and extracted **sonar-scanner-3.3.0.1492-macosx**.  That is my SONAR_HOME.  Do you advise using the other link instead?

**Comment by arturbosch** [comment]
Yes, this plugin is meant to work with sonarqube.
I have not used sinar-scanner myself.
